// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMAaBok2R2gj0UV2HGZO6yt8CAcnxTPKk',
    appId: '1:226030806435:web:4ea77a3e868584a6a36616',
    messagingSenderId: '226030806435',
    projectId: 'vivordo-health',
    authDomain: 'vivordo-health.firebaseapp.com',
    storageBucket: 'vivordo-health.firebasestorage.app',
    measurementId: 'G-2BM9R28LWD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzmw4Bs7i5w9vO3PF4YARWo7Mx3-zcw1Q',
    appId: '1:226030806435:android:5ea4e7a9ff8cc3a6a36616',
    messagingSenderId: '226030806435',
    projectId: 'vivordo-health',
    storageBucket: 'vivordo-health.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFzLeHFVO2jNbwBEHarMnF0rHu25IetMs',
    appId: '1:226030806435:ios:4e505f002fb984eda36616',
    messagingSenderId: '226030806435',
    projectId: 'vivordo-health',
    storageBucket: 'vivordo-health.firebasestorage.app',
    iosClientId: '226030806435-d4nqtstrlhtm1cltipnat2bpo5eqn0mj.apps.googleusercontent.com',
    iosBundleId: 'com.example.vivordoHealth',
  );

}