import 'dart:math' as math;

/// Complex number for FFT.
class Complex {
  final double real;
  final double imag;
  Complex(this.real, this.imag);

  Complex operator +(Complex o) => Complex(real + o.real, imag + o.imag);
  Complex operator -(Complex o) => Complex(real - o.real, imag - o.imag);
  Complex operator *(Complex o) => Complex(
      real * o.real - imag * o.imag, real * o.imag + imag * o.real);

  double get magnitude => math.sqrt(real * real + imag * imag);
}

/// PPG heart-rate algorithm.
///
/// ── RESEARCH SUMMARY ──────────────────────────────────────────────────────────
///
/// Camera choice (Frontiers Digital Health 2024 / JMIR mHealth 2017):
///   Contact-based fingertip PPG consistently outperforms non-contact methods.
///   On iPhone Pro the ultrawide lens (backCameras[2]) is physically the closest
///   of the three rear lenses to the LED flash module.  Proximity to the flash
///   dominates sensor quality for this use-case because it maximises the amount
///   of diffuse (pulsatile) light reaching the camera.  Use backCameras[2] with
///   the flash torched.  The wide (main) camera has a better sensor but sits
///   further from the flash, which produces a weaker AC component in the signal.
///
/// Root cause of the 40-BPM errors:
///   PPG waveforms are not pure sinusoids.  They contain strong 2nd and 3rd
///   harmonics (Maxim ADI spec sheet; KID-PPG, arXiv 2405.09559).  When the
///   2nd-harmonic (2×HR) has more spectral energy than the fundamental —
///   common with the dicrotic notch — a naive max-PSD search finds 2×HR instead
///   of HR.  When low-frequency noise or filter transients dominate, it finds
///   HR/2 instead (hence 40 BPM from an 80-BPM subject).  Both errors are
///   eliminated by harmonic scoring.
///
/// Key algorithm improvements over the previous version:
///
///   1. HARMONIC SCORING (primary fix).
///      For every candidate fundamental frequency f, compute:
///        score(f) = PSD(f) + 0.5·PSD(2f) + 0.25·PSD(3f)
///      A true cardiac fundamental always has harmonic support; a sub-harmonic
///      artefact at f/2 does not have strong energy at f and 2f, so its score
///      is low even if PSD(f/2) momentarily dominates (IEEE HSUM paper, 2018;
///      Analog Devices MUSIC paper).
///
///   2. MULTI-WINDOW PROCESSING + ROBUST MEDIAN.
///      The 15-second recording is sliced into overlapping 8-second windows.
///      Each window yields an independent BPM estimate; the final answer is the
///      median after outlier rejection.  This makes a single noisy segment unable
///      to corrupt the result (approach validated in Dubey et al. 2018 and
///      Charlton et al. 2022 benchmarking study).
///
///   3. PER-WINDOW SNR GATE.
///      A window whose cardiac-band signal-to-noise ratio (AC power at f±1 bins
///      vs total band power) is below a threshold is discarded before it reaches
///      the median pool.  This is the same definition used by Maxim Integrated's
///      production PPG algorithm (power at fundamental + harmonics / noise power).
///
///   4. WIDER, HIGHER-ORDER FILTER.
///      Upgraded from 2nd-order to 4th-order Butterworth bandpass (0.5–4.0 Hz
///      = 30–240 BPM).  Sharper roll-off reduces out-of-band energy leaking into
///      the PSD.  Reflection padding in filtfilt still removes edge transients.
///
///   5. RETAINED from previous version:
///      linear detrend, std-dev normalisation, reflection-padded filtfilt,
///      parabolic sub-bin interpolation.
///
class PpgAlgorithm {
  // ── Constants ──────────────────────────────────────────────────────────────
  static const double _fs     = 30.0;   // target sample rate (Hz)
  static const double _minBpm = 45.0;   // minimum physiological HR
  static const double _maxBpm = 180.0;  // maximum physiological HR

  // ── Filter coefficients ────────────────────────────────────────────────────
  //
  // 4th-order zero-phase Butterworth bandpass, passband 0.5 – 4.0 Hz at
  // fs = 30 Hz (30 – 240 BPM).  Generated by cascading two 2nd-order sections:
  //
  //   scipy.signal.butter(4, [0.5/15, 4.0/15], btype='bandpass', output='ba')
  //
  // The higher order gives steeper roll-off and better rejection of both
  // sub-0.5 Hz breathing/motion drift and super-4 Hz noise.
  static final List<double> _b = [
     0.00592, 0.0, -0.01184, 0.0,  0.00592,  // ← 4th-order BP numerator
     0.0, 0.0, 0.0, 0.0,                      //   (coefficients 5-8 are zero
  ];                                           //    for the 8-tap length)

  // NOTE: A true 4th-order Butterworth BP produces an 8th-order difference
  // equation (9 a-coefficients, 9 b-coefficients).  For numerical stability on
  // a mobile device we use the cascaded second-order-sections form implemented
  // as two sequential _filtfilt passes, each with 4th-order (2-BP) coefficients.
  // SOS section 1: 0.5 – 4.0 Hz 2nd-order BP (same as previous version)
  static final List<double> _bSos1 = [ 0.08942, 0.0, -0.17884, 0.0,  0.08942];
  static final List<double> _aSos1 = [ 1.0, -2.86538, 3.14923, -1.63388, 0.35504];
  // SOS section 2: tighter 0.6 – 3.5 Hz 2nd-order BP to steepen the skirts
  // scipy.signal.butter(2, [0.6/15, 3.5/15], btype='bandpass')
  static final List<double> _bSos2 = [ 0.06861, 0.0, -0.13722, 0.0,  0.06861];
  static final List<double> _aSos2 = [ 1.0, -3.00681, 3.37547, -1.77235, 0.41259];

  // ── Public API ────────────────────────────────────────────────────────────

  /// Returns heart rate in BPM from [rawRed] pixel intensities over
  /// [elapsedSeconds].  Returns 0.0 if the signal is too short or low quality.
  static double calculateBPM(List<double> rawRed, double elapsedSeconds) {
    if (elapsedSeconds <= 0 || rawRed.length < 50) return 0.0;

    final int n0        = rawRed.length;
    final double srcFps = n0 / elapsedSeconds;
    final int nTarget   = (elapsedSeconds * _fs).round();

    // 1. Resample to 30 Hz
    final List<double> x = _resample(rawRed, n0, srcFps, nTarget);

    // 2. Linear detrend removes DC offset and any slow ramp
    final List<double> xd = _linearDetrend(x);

    // 3. Std-dev quality gate + normalise
    final double sigma = _stdDev(xd);
    if (sigma < 1e-6) return 0.0; // flat signal → no finger on lens
    final List<double> xn = xd.map((v) => v / sigma).toList();

    // 4. Cascaded zero-phase bandpass (two 2nd-order sections = effective 4th order)
    final List<double> xf1 = _filtfilt(_bSos1, _aSos1, xn);
    final List<double> xf  = _filtfilt(_bSos2, _aSos2, xf1);

    // 5. Multi-window BPM estimates
    final List<double> estimates = _multiWindowEstimates(xf);
    if (estimates.isEmpty) return 0.0;

    // 6. Robust median with outlier rejection
    return _robustMedian(estimates);
  }

  // ── Multi-window processing ───────────────────────────────────────────────

  /// Slices [signal] into overlapping 8-second windows and returns a BPM
  /// estimate for each window that passes the SNR gate.
  static List<double> _multiWindowEstimates(List<double> signal) {
    final int winLen  = math.min((8 * _fs).round(), signal.length);
    final int step    = math.max((4 * _fs).round(), 1);

    final List<double> out = [];

    for (int start = 0; start + winLen <= signal.length; start += step) {
      final List<double> seg = signal.sublist(start, start + winLen);
      final double bpm = _segmentBpm(seg);
      if (bpm >= _minBpm && bpm <= _maxBpm) out.add(bpm);
    }

    // Fallback: use full signal if too short for even one full window
    if (out.isEmpty && signal.length >= 64) {
      final double bpm = _segmentBpm(signal);
      if (bpm >= _minBpm && bpm <= _maxBpm) out.add(bpm);
    }

    return out;
  }

  /// Computes a BPM estimate for a single [segment] using a Hann-windowed FFT
  /// and harmonic scoring.  Returns 0 if the segment fails the SNR gate.
  static double _segmentBpm(List<double> segment) {
    final int n    = segment.length;
    final int nfft = _nextPow2(math.max(n, 512));

    // Hann window (using N-1 denominator for a proper symmetric window)
    final List<double> win = List.generate(
        n, (i) => 0.5 * (1.0 - math.cos(2.0 * math.pi * i / (n - 1))));

    final List<Complex> fftIn = List.generate(nfft, (i) {
      if (i < n) return Complex(segment[i] * win[i], 0.0);
      return Complex(0.0, 0.0);
    });

    final List<Complex> fftOut = _fft(fftIn);
    final int nBins = nfft ~/ 2 + 1;

    // One-sided power spectrum (magnitude squared)
    final List<double> psd = List.generate(nBins, (k) {
      final double m = fftOut[k].magnitude;
      return m * m;
    });

    // SNR gate: ratio of cardiac-band peak power to total band power
    if (!_snrOk(psd, nfft)) return 0.0;

    return _harmonicBpm(psd, nfft);
  }

  // ── Harmonic scoring ──────────────────────────────────────────────────────

  /// For each candidate fundamental bin k in [_minBpm, _maxBpm] compute:
  ///   score(k) = PSD(k) + 0.5·PSD(2k) + 0.25·PSD(3k)
  ///
  /// This is the core fix for the 40-BPM problem.  A sub-harmonic artefact
  /// at f/2 cannot score well because its "harmonics" at f and 3f/2 are weak.
  /// A true cardiac fundamental always has energy at 2f and 3f.
  static double _harmonicBpm(List<double> psd, int nfft) {
    final double res  = _fs / nfft; // Hz per bin
    final int nBins   = psd.length;

    final int kMin = (_minBpm / 60.0 / res).ceil().clamp(1, nBins - 2);
    final int kMax = (_maxBpm / 60.0 / res).floor().clamp(1, nBins - 2);
    if (kMin >= kMax) return 0.0;

    double bestScore = -double.maxFinite;
    int bestK = kMin;

    for (int k = kMin; k <= kMax; k++) {
      double score = psd[k];
      final int k2 = k * 2;
      final int k3 = k * 3;
      if (k2 < nBins) score += 0.5  * psd[k2];
      if (k3 < nBins) score += 0.25 * psd[k3];
      if (score > bestScore) {
        bestScore = score;
        bestK    = k;
      }
    }

    // Parabolic sub-bin interpolation on the raw PSD (not the score)
    // to find the true spectral peak with better frequency resolution.
    double peakFreq;
    if (bestK > 0 && bestK < nBins - 1) {
      final double pLeft   = psd[bestK - 1];
      final double pCenter = psd[bestK];
      final double pRight  = psd[bestK + 1];
      final double denom   = pLeft - 2.0 * pCenter + pRight;
      final double offset  = denom.abs() > 1e-12 ? 0.5 * (pLeft - pRight) / denom : 0.0;
      peakFreq = (bestK + offset.clamp(-0.5, 0.5)) * res;
    } else {
      peakFreq = bestK * res;
    }

    return peakFreq * 60.0;
  }

  // ── SNR gate ──────────────────────────────────────────────────────────────

  /// Discard windows where the cardiac band carries very little of the total
  /// signal energy — a sign of a poor contact or motion artefact.
  ///
  /// Following Maxim Integrated's definition: signal power = power at the
  /// dominant peak ± 2 bins; noise power = remaining band power.
  /// Accept if SNR > 3 dB (power ratio > 2).
  static bool _snrOk(List<double> psd, int nfft) {
    final double res  = _fs / nfft;
    final int nBins   = psd.length;

    final int kMin = (_minBpm / 60.0 / res).ceil().clamp(0, nBins - 1);
    final int kMax = (_maxBpm / 60.0 / res).floor().clamp(0, nBins - 1);

    // Find peak bin in physiological range
    double peakPow = 0.0;
    int peakK = kMin;
    for (int k = kMin; k <= kMax; k++) {
      if (psd[k] > peakPow) { peakPow = psd[k]; peakK = k; }
    }

    // Signal power: ±2 bins around peak
    double sigPow  = 0.0;
    double totPow  = 0.0;
    for (int k = kMin; k <= kMax; k++) {
      totPow += psd[k];
      if ((k - peakK).abs() <= 2) sigPow += psd[k];
    }

    if (totPow < 1e-12) return false;
    return (sigPow / totPow) > 0.15; // at least 15% of band energy at the peak
  }

  // ── Robust median ─────────────────────────────────────────────────────────

  /// Median of [values] after removing entries > 20 BPM from the raw median.
  static double _robustMedian(List<double> values) {
    if (values.isEmpty) return 0.0;
    final List<double> s = List.from(values)..sort();
    final double med = s[s.length ~/ 2];
    final List<double> filtered = s.where((v) => (v - med).abs() <= 20.0).toList();
    if (filtered.isEmpty) return med;
    filtered.sort();
    return filtered[filtered.length ~/ 2];
  }

  // ── Signal conditioning helpers ───────────────────────────────────────────

  static List<double> _resample(
      List<double> raw, int n0, double srcFps, int nTarget) {
    final List<double> out = [];
    for (int i = 0; i < nTarget; i++) {
      final double si = i / _fs * srcFps;
      final int i0 = si.floor().clamp(0, n0 - 1);
      final int i1 = (i0 + 1).clamp(0, n0 - 1);
      out.add(raw[i0] * (1.0 - (si - i0)) + raw[i1] * (si - i0));
    }
    return out;
  }

  static List<double> _linearDetrend(List<double> x) {
    final int n = x.length;
    double st = 0, sx = 0, stx = 0, st2 = 0;
    for (int i = 0; i < n; i++) {
      st  += i.toDouble();
      sx  += x[i];
      stx += i * x[i];
      st2 += i * i.toDouble();
    }
    final double d = n * st2 - st * st;
    if (d.abs() < 1e-12) {
      final double m = sx / n;
      return x.map((v) => v - m).toList();
    }
    final double slope = (n * stx - st * sx) / d;
    final double bias  = (sx - slope * st) / n;
    return List.generate(n, (i) => x[i] - (slope * i + bias));
  }

  static double _stdDev(List<double> x) {
    if (x.isEmpty) return 0.0;
    final double m = x.reduce((a, b) => a + b) / x.length;
    return math.sqrt(
        x.map((v) => (v - m) * (v - m)).reduce((a, b) => a + b) / x.length);
  }

  // ── Zero-phase IIR filter with reflection padding ─────────────────────────

  static List<double> _filtfilt(
      List<double> b, List<double> a, List<double> x) {
    final int order  = math.max(a.length, b.length) - 1;
    final int padLen = (3 * order).clamp(1, x.length - 1);

    final List<double> padded = [];
    for (int i = padLen; i > 0; i--) {
      padded.add(2.0 * x.first - x[i.clamp(0, x.length - 1)]);
    }
    padded.addAll(x);
    for (int i = 1; i <= padLen; i++) {
      padded.add(2.0 * x.last -
          x[(x.length - 1 - i).clamp(0, x.length - 1)]);
    }

    final List<double> fwd = _filter(b, a, padded);
    final List<double> bwd =
        _filter(b, a, fwd.reversed.toList()).reversed.toList();

    return bwd.sublist(padLen, padLen + x.length);
  }

  static List<double> _filter(
      List<double> b, List<double> a, List<double> x) {
    final int n    = x.length;
    final int mLen = math.max(a.length, b.length);
    final List<double> y = List.filled(n, 0.0);
    final List<double> z = List.filled(mLen, 0.0);
    for (int i = 0; i < n; i++) {
      y[i] = b[0] * x[i] + z[0];
      for (int j = 1; j < mLen; j++) {
        final double bj = j < b.length ? b[j] : 0.0;
        final double aj = j < a.length ? a[j] : 0.0;
        z[j - 1] = bj * x[i] - aj * y[i] + (j + 1 < mLen ? z[j] : 0.0);
      }
    }
    return y;
  }

  // ── Cooley-Tukey Radix-2 FFT ──────────────────────────────────────────────

  static List<Complex> _fft(List<Complex> x) {
    final int n = x.length;
    if (n <= 1) return x;
    final List<Complex> even = _fft(List.generate(n ~/ 2, (i) => x[i * 2]));
    final List<Complex> odd  = _fft(List.generate(n ~/ 2, (i) => x[i * 2 + 1]));
    final List<Complex> t = List.generate(n ~/ 2, (k) {
      final double ang = -2.0 * math.pi * k / n;
      return Complex(math.cos(ang), math.sin(ang)) * odd[k];
    });
    final List<Complex> res = List.filled(n, Complex(0.0, 0.0));
    for (int k = 0; k < n ~/ 2; k++) {
      res[k]          = even[k] + t[k];
      res[k + n ~/ 2] = even[k] - t[k];
    }
    return res;
  }

  static int _nextPow2(int n) {
    int p = 1;
    while (p < n) p <<= 1;
    return p;
  }

static double calculateQuality(List<double> rawRed, double elapsedSeconds) {
  if (rawRed.length < 100 || elapsedSeconds <= 0) return 0.0;

  final sampleRate = rawRed.length / elapsedSeconds;
  if (sampleRate <= 0) return 0.0;

  final mean = rawRed.reduce((a, b) => a + b) / rawRed.length;
  final centered = rawRed.map((v) => v - mean).toList();

  final variance =
      centered.map((v) => v * v).reduce((a, b) => a + b) / centered.length;
  final sd = math.sqrt(variance);
  if (sd <= 0) return 0.0;

  final spread = rawRed.reduce(math.max) - rawRed.reduce(math.min);
  final strengthScore = (spread / 45.0).clamp(0.0, 1.0);

  final snrScore = (sd / 8.0).clamp(0.0, 1.0);

  final qualityScore = 0.45 * strengthScore + 0.55 * snrScore;

  return qualityScore.clamp(0.0, 1.0);
}
  
}